### ISSUE TITLE
Unable to change subscription status.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/widget-financial-table#100]
I have been unsuccessful at changing the subscription status of this widget.

To replicate - 
1) Log into test company
2) Provide Robb w/company ID, he will add the beta widget
3) Add widget to presentation, confirm trial is available
4) Confirm widget settings shows Trial Available - Start Trial (see issue #99 )
5) Save and publish, add to schedule and display. Notice that display shows Rise Vision default presentation. Widget shows not subscribed.
6) Widget will not change subscription status, and will not display in preview/player.  Widget always shows as Trial Available/Not Subscribed.

http://www.screencast.com/t/eKVP2ay40dZz

How it should function - 
1) Log into test company
2) Provide Robb w/company ID, he will add the beta widget
3) Add widget to presentation, confirm trial is available
4) Confirm widget settings shows Trial Available - Start Trial
5) Click start trial, widget settings should show Trial - XX Days remaining
6) Widget should display in presentation

**Comment by alex-deaconu** [comment]
@btfrise @robb-price the issue had to do with HTTPs which is used by the Financial Table Widget BETA (urls configured in the RVA). I've fixed that issue, however, going forward we should also make sure the Financial Table Widget (production version) is set to use HTTPs for its URLs. However don't update it until the new Widget version is released, as the old version doesn't work with HTTPs.
The issue should now be fixed, ie the Widget should show up correctly in the presentation.
Thanks.

**Comment by btfrise** [comment]
@alex-deaconu I am still unable to get this widget to change subscription status at all. I've outline the exact inssue for clarification in this video - http://www.screencast.com/t/qk9Fk3wFnh4B

**Comment by alex-deaconu** [comment]
@btfrise your Display is showing demo content. Please re-verify. Thanks.

**Comment by btfrise** [comment]
@alex-deaconu sorry about that, I loaded the wrong player on that demo. The correct player shows no content and does not change the subscription status from not subscribed.

**Comment by btfrise** [comment]
@alex-deaconu It just began appearing on my display and status changed to on trial. Was something changed recently? Could the old version have been cached even though I cleared my local cache?

**Comment by alex-deaconu** [comment]
@btfrise I re-deployed the Widget to fix issue #99, but it was working for me correctly from before. Maybe it was a caching issue.
